# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Build and Deploy Site

on:
  push:
    branches: [master]

env:
  PANDOC_VERSION: 3.0.1
  WKHTMLTOPDF_VERSION: 0.12.6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-pandoc@v2
        with:
          pandoc-version: ${{ env.PANDOC_VERSION }}
      - name: Setup weasyprint
        run: sudo apt-get update && sudo apt-get install -y weasyprint
      - name: Generate files
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: site
          path: |
            index.html
            resume.pdf
            resume.txt
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: Production
      url: https://cv.jlindsey.me
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: site
          path: site
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DEPLOY_KEY }}
          name: id_ed25519
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILNET_AUTHKEY }}
      - run: |
          cp -r css site
          rsync -avz --delete site/ root@cv-web-server:/mnt/data/web/
