# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Terraform

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths: ["tf/*"]

env:
  TF_IN_AUTOMATION: 1
  AWS_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - uses: terraform-linters/setup-tflint@v3
      - run: terraform init
        working-directory: tf
      - run: terraform validate
        working-directory: tf
      - name: Run TFLint
        run: |
          tflint --init
          tflint -f compact

  apply:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
      - run: terraform init
        working-directory: tf
      - run: terraform plan -out plan.tfplan
        working-directory: tf
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}
      - run: terraform apply plan.tfplan
        working-directory: tf
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          TAILSCALE_API_KEY: ${{ secrets.TAILSCALE_API_KEY }}
